## 1
name: detekt
## 2
on:
#  push:
  pull_request:

## 3
jobs:
  detekt:
    ## 4
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v2
      - name: "detekt"
        uses: natiginfo/action-detekt-all@1.20.0
        with:
            args: --config configs/detekt/default_detekt.yml
